# Developer logging configuration
#
# https://github.com/s-fairchild/bash-logger/blob/30e2020b996efd4ce82927099011c5b9ad52bc7c/docs/configuration.md

[logging]
level = DEBUG
verbose = true
color = always
format = [%l] %d - %m
log_file = /tmp/dev.log
stderr_level = DEBUG
